import {
  BadgeDollarSign,
  Bot,
  BrainCircuit,
  BookOpenText,
  Bookmark,
  Calculator,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronUp,
  CircleCheck,
  CircleX,
  ClipboardList,
  Copy,
  Download,
  FileDown,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  ImagePlus,
  Info,
  Landmark,
  Loader2,
  MessageCircle,
  MoreHorizontal,
  Pencil,
  Percent,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Settings2,
  Sparkles,
  TableProperties,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  WalletCards,
  WandSparkles,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react"

export const iconMap = {
  ai: Sparkles,
  aiBot: Bot,
  aiMessage: MessageCircle,
  aiThinking: BrainCircuit,
  batch: FolderOpen,
  calculator: Calculator,
  cashflow: TrendingUp,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  close: X,
  copy: Copy,
  cost: Landmark,
  delete: Trash2,
  document: FileText,
  download: Download,
  edit: Pencil,
  error: CircleX,
  exportReport: FileDown,
  file: FileText,
  folder: FolderOpen,
  generate: WandSparkles,
  imageUpload: ImagePlus,
  importExcel: Upload,
  info: Info,
  irr: Percent,
  loading: Loader2,
  module: ChartNoAxesCombined,
  npv: BadgeDollarSign,
  parameters: Settings2,
  project: ClipboardList,
  presets: BookOpenText,
  presetLibrary: Bookmark,
  reverse: RotateCcw,
  revenue: WalletCards,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  spreadsheet: FileSpreadsheet,
  success: CircleCheck,
  tableProperties: TableProperties,
  warning: TriangleAlert,
  more: MoreHorizontal,
  quickAction: Zap,
} as const satisfies Record<string, LucideIcon>

export type AppIconName = keyof typeof iconMap
