import type { AiChatMessage } from './types';

// This is a conservative UI invitation, never authorization to save or generate.
// Require a direct request, not just a template name, a read query or model output.
const form = '(?:ICT项目)?需求(?:导入|分析)?表(?:模板)?';
const action = '(?:生成|填写|填好|填|输入|录入|补充|补齐|完善|制作|导出)';
const timing = '(?:现在|接下来|这次|先|开始|继续)?';
const request = `(?:(?:请|麻烦|劳驾)?(?:你)?(?:帮我|给我|为我)?|(?:能不能|能否|可以|能)(?:请)?(?:你)?(?:帮我|给我)|我${timing}(?:想|要|需要|准备|打算|会|将)(?:要|会)?(?:请你|让你)?(?:帮我)?)`;
const task = new RegExp(`^(?:${timing}${request}|${request}${timing})${action}(?:一下|一份|一张|这份|这张|这个|本项目的|项目的|一份本项目的)?${form}`);
const namedTask = new RegExp(`^(?:这个|这份|这张)?${form}(?:的内容)?(?:${request}${timing})${action}`);

export function isDemandFormRequest(content: string): boolean {
  // Quoted instructions and pasted documents are data, not a new request.
  const text = content
    .replace(/```[\s\S]*?(?:```|$)/g, '')
    .replace(/^\s*>.*$/gm, '')
    .replace(new RegExp(`[“「"](${form})[”」"]`, 'g'), '$1')
    .replace(/[“「][\s\S]*?[”」]|"[^"\n]*"/g, '')
    .replace(/[《》\t ]/g, '');
  if (/(?:不要|不用|无需|别|暂不|先不).{0,12}(?:上传|补图|图片|附件|提醒)/.test(text)) return false;
  return text.split(/[，,。.!！?？;；\n]/).some(clause =>
    !/(?:如何|怎么|怎样|什么|会不会|能不能|是否|为什么|只是|只想|只问)/.test(clause.replace(/^(?:能不能|能否)/, ''))
    && (task.test(clause) || namedTask.test(clause)));
}

/** Only the latest user turn can invite cards. History is not a permanent task latch. */
export function wantsDemandImageCompletion(messages: readonly AiChatMessage[]): boolean {
  for (let index = messages.length - 1; index >= 0; index--) {
    if (messages[index].role === 'user') return isDemandFormRequest(messages[index].content);
  }
  return false;
}

export function demandImageCompletionPrompt(requested: boolean): string {
  return requested
    ? 'The current user turn explicitly requests demand-form filling or generation. The chat can show labeled upload cards for missing demand-template images after checking saved state. Only guide the user to these cards when images are actually missing; never claim a file was saved or generated by this invitation.'
    : 'No demand-image upload invitation is active for this turn. Binding a project, general conversation, read-only template questions and ordinary chat image attachments do not request form filling or generation. Do not proactively ask for demand-template images or claim upload cards are visible. If the user explicitly wants to fill or generate the demand form, they can say so in the next message. Answer their current question without adding an upload reminder.';
}
